resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [nodes:children]
    managers
    
    [managers]
    ${var.vm_name}.netology.cloud ansible_host=${yandex_compute_instance.yc-node.network_interface.0.nat_ip_address}

    DOC


  filename = "ansible/inventory"
}